spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/testdb
    username: pguser
    password: secret
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jakarta.persistence.validation.mode: auto
      hibernate.format_sql: true
logging:
  level:
    org.springframework.boot.context.config: DEBUG
